default: &default
  adapter: postgresql
  username: postgres
  password:
  encoding: unicode
  host: <%= ENV['PGHOST'] || 'localhost' %>
  port: <%= ENV['PGPORT'] || 5432 %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: xeriscape_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: xeriscape_test
  url: <%= ENV['DATABASE_URL'] %>

heroku: &heroku
  pool: <%= ENV["DB_POOL"] || 5 %>

production:
  <<: *heroku
